/* ===================================================================
   Domain 6 — Practical Application — Python
   Înlocuiește array-ul de mai jos cu întrebările reale (vezi README,
   secțiunea 4, pentru schema fiecărui tip de întrebare — inclusiv câmpul
   opțional "explanation").
   ⚠️ Variabila trebuie declarată cu "var" (nu "const"/"let").
   =================================================================== */

var QUESTIONS_D6_PRACTICAL = [
  {
    id: "d6_practical_01",
    type: "blank",
    question: "Evaluate the following code, fill in the function that will return the mantissa for variable b, and assign the value to variable c such that b = c × (2 ^ exponent).<br><br><code>import math<br><br>a = 5<br>b = 7<br><br>c, _ = math.{{1}}(b) #The underscore ignores the exponent part</code>",
    image: null,
    options: [],
    correct: ["frexp"],
  },
  {
    id: "d6_practical_02",
    type: "blank",
    question: "For the following code example, fill in the method and arguments necessary to assign two unique random values from the woods variable to the wood variable.<br><br><code># Import the random module<br>import random<br><br># Initialize a list named woods with different types of wood<br>woods = ['Plywood', 'Oak', 'Pine', 'Maple']<br><br># Randomly select two types of wood from the woods list<br>wood = random.{{1}}<br><br># Print the randomly selected wood types<br>print(wood)</code>",
    image: null,
    options: [],
    correct: ["sample(woods, 2)"],
  },
  {
    id: "d6_practical_03",
    type: "match",
    question: "The following code aims to accomplish two things:<br><br>1. List the current working directory<br>2. From the current directory, list any file that ends in .png.<br><br>Using drag and drop, fill in the three missing pieces of code.<br><br><code># Import the os module for operating system operations<br>import os<br><br># Print the current working directory<br>print(\"Your current directory is:\", os.____())<br><br># Loop through each file in the current working directory<br>for pic_file in os.____():<br><br>&nbsp;&nbsp;# Check if the file ends with '.png'<br>&nbsp;&nbsp;if pic_file.____('.png'):<br><br>&nbsp;&nbsp;&nbsp;&nbsp;# Print the name of the PNG file<br>&nbsp;&nbsp;&nbsp;&nbsp;print(pic_file)</code>",
    image: null,
    pairs: [
      "print(\"Your current directory is:\", os.____())",
      "for pic_file in os.____():",
      "if pic_file.____('.png'):"
    ],
    options: ["listdir", "getcwd", "endswith"],
    correct: ["getcwd", "listdir", "endswith"],
  },
  {
    id: "d6_practical_04",
    type: "blank",
    question: "Finish the following code so that variable c is the square root of variable b.<br><br><code>import math<br>a = 5<br>b = 12<br>c = math.{{1}}(b)</code>",
    image: null,
    options: [],
    correct: ["sqrt"],
  },
  {
    id: "d6_practical_05",
    type: "blank",
    question: "For this line of code, which built-in Python module needs to be imported? Remember to use the correct capitalization.<br><br><code>text_stream.seek(0)</code><br><br>Answer:{{1}}",
    image: null,
    options: [],
    correct: ["io"],
  },
  {
    id: "d6_practical_06",
    type: "blank",
    question: "In the following code, the text_stream variable is being set up to write text to memory. Fill in the blank with the method needed to open a session of writing text to memory.<br><br><code>text_stream = io.{{1}}()</code>",
    image: null,
    options: [],
    correct: ["StringIO"],
  },
  {
    id: "d6_practical_07",
    type: "blank",
    question: "Fill in the Python module and method needed to see if a file named log.txt is present in the current directory.<br><br><code>if {{1}}('log.txt') #Check whether log.txt exists in current directory<br>message = open('log.txt', 'r')</code>",
    image: null,
    options: [],
    correct: ["os.path.isfile"],
  },
  {
    id: "d6_practical_08",
    type: "blank",
    question: "Evaluate the following code. What will be the value of variable c?<br><br><code>import math # Import the math module<br><br>a = -5.5 # Initialize a with a negative floating-point number<br>b = 7.25 # Initialize b with a positive floating-point number<br><br>c = math.ceil(b) # Apply a math operation to b and store the result in c</code><br><br>Answer: {{1}}",
    image: null,
    options: [],
    correct: ["8"],
  },
  {
    id: "d6_practical_09",
    type: "blank",
    question: "A developer wants to show a date in mm-dd-yyyy format. In the current code example, fill in the necessary method to enable the current_date variable to display in the wanted format.<br><br><code>import datetime # Import the datetime library<br><br>current_date = datetime.datetime.now() # Get the current date and time<br><br># Format the date to mm-dd-yyyy and display it<br>print(\"Current date: \", current_date.{{1}}(\"%m-%d-%Y\"))</code>",
    image: null,
    options: [],
    correct: ["strftime"],
  },
  {
    id: "d6_practical_10",
    type: "blank",
    question: "The following code needs to set the current_time variable to the current date and time. Fill in the module, class, and method needed to return the current date and time.<br><br><code>import datetime # Import the datetime module<br><br>current_time = {{1}} # Get current date and time</code>",
    image: null,
    options: [],
    correct: ["datetime.datetime.now()"],
  },
  {
    id: "d6_practical_11",
    type: "match",
    question: "In the following code, drag in the methods needed to establish a file and folder path on which the if statement will check to see if the file exists in the given folder.<br><br><code>file_path = os.path.____('logs', 'log1.txt') # Establish path to log1.txt inside logs folder<br><br>if os.path.____(file_path): # Check if path is valid<br>&nbsp;&nbsp;print('File exists.')</code>",
    image: null,
    pairs: [
      "file_path = os.path.____('logs', 'log1.txt') # Establish path to log1.txt inside logs folder",
      "if os.path.____(file_path): # Check if path is valid"
    ],
    options: ["exists", "join"],
    correct: ["join", "exists"],
  },
  {
    id: "d6_practical_12",
    type: "blank",
    question: "Evaluate the following code and then add the missing function that will then return the whole number of the square root of variable c.<br><br><code>import math<br><br>c = 13<br>d = -3<br><br>print(math.{{1}}(c))</code>",
    image: null,
    options: [],
    correct: ["isqrt"],
  },
  {
    id: "d6_practical_13",
    type: "blank",
    question: "In the following code, fill in the method necessary to rearrange the breads list in a random order without any recurrence.<br><br><code># Import the random module<br>import random<br><br># Initialize a list named breads with different types of bread<br>breads = ['White', 'Wheat', 'Rye', 'Sourdough']<br><br># Rearrange the breads list in random order<br>random.{{1}}(breads)<br><br># Print the rearranged list<br>print(breads)</code>",
    image: null,
    options: [],
    correct: ["shuffle"],
  },
  {
    id: "d6_practical_14",
    type: "blank",
    question: "Evaluate the following code and then indicate the value for variable c.<br><br><code>import math # Import the math module<br><br>a = 7 # Initialize variable a with an integer value<br>b = 3 # Initialize variable b with another integer value<br><br>c = math.fmod(a, b) # Apply a math operation on a and b and store the result in c</code><br><br>Answer: {{1}}",
    image: null,
    options: [],
    correct: ["1.0"],
  },
  {
    id: "d6_practical_15",
    type: "blank",
    question: "Analyze the following code. If the date returned falls on a Sunday, what will be the value of the current_weekday variable?<br><br><code>import datetime # Import the datetime library<br><br>current_day = datetime.datetime.now() # Get the current date and time<br>current_weekday = current_day.weekday() # Get the weekday</code><br><br>Answer: {{1}}",
    image: null,
    options: [],
    correct: ["6"],
  },
  {
    id: "d6_practical_16",
    type: "blank",
    question: "In the following code, add the function necessary to return the next lowest integer value for variable b.<br><br><code>import math # Import the mathmodule<br><br>a = -5.5 # Initialize a with a negative floating-pointnumber<br>b = 7.25 # Initialize b with a positive floating-pointnumber<br><br>c = math.{{1}}(b) #Apply a math operation to b and store the result in c</code>",
    image: null,
    options: [],
    correct: ["floor"],
  },
  {
    id: "d6_practical_17",
    type: "blank",
    question: "Evaluate the following code and then fill in the method necessary to return just the integer portion of variable a without converting the variable to an integer.<br><br><code>import math # Import the mathmodule<br><br>a = 4.4 # Initialize a with a floating-point number<br>b = 6.78 # Initialize b with another floating-point number<br><br>c = math.{{1}}(a) #Apply a math operation to a to obtain its integer portion</code>",
    image: null,
    options: [],
    correct: ["trunc"],
  },
  {
    id: "d6_practical_18",
    type: "blank",
    question: "Which Python math constant returns a value of 3.14159?<br><br>Answer: {{1}}",
    image: null,
    options: [],
    correct: ["pi"],
  },
  {
    id: "d6_practical_19",
    type: "blank",
    question: "Evaluate the following code and then fill in the function and arguments needed to have variable c equal to b raised to the power of a.<br><br><code>import math<br><br>a = 4<br>b = 5<br><br>c = math.{{1}}(b, a)</code>",
    image: null,
    options: [],
    correct: ["pow"],
  },
  {
    id: "d6_practical_20",
    type: "blank",
    question: "Fill in the method necessary to assign variable x a random number between 0 and 1.<br><br><code># Import the random module<br>import random<br><br># Assign variable x a random float number between 0 and 1<br>x = {{1}}</code>",
    image: null,
    options: [],
    correct: ["random.random()"],
  },
  {
    id: "d6_practical_21",
    type: "blank",
    question: "Evaluate the following code:<br><br><code>import math<br><br>b = float(\"NaN\")<br>c = math.isnan(b)</code><br><br>What is the value of c?<br><br>Answer: {{1}}",
    image: null,
    options: [],
    correct: ["True"],
  },
  {
    id: "d6_practical_22",
    type: "blank",
    question: "Evaluate the following code and then fill in the method needed to get the floating absolute value of variable b.<br><br><code>import math<br><br>a = 5<br>b = -2.5<br><br>c = math.{{1}}(b) # Calculate floating absolute value of b</code>",
    image: null,
    options: [],
    correct: ["fabs"],
  },
  {
    id: "d6_practical_23",
    type: "blank",
    question: "In the following code, fill in the method needed to randomly choose a single value from the list of woods in the woods variable.<br><br><code># Import the random module<br>import random<br><br># Initialize a list named woods with different types of wood<br>woods = ['Plywood', 'Oak', 'Pine', 'Maple']<br><br># Randomly select a single type of wood from the woods list<br>wood = random.{{1}}(woods)<br><br># Print the randomly selected wood<br>print(wood)</code>",
    image: null,
    options: [],
    correct: ["choice"],
  },
  {
    id: "d6_practical_24",
    type: "blank",
    question: "Evaluate the following code and then fill in the module and method needed to end the running code gracefully.<br><br><code>turns = 1<br>while turns < 5:<br>&nbsp;&nbsp;print(\"Gamein progress\")<br>&nbsp;&nbsp;turns += 1 #Increment turn number<br>{{1}}() # Quit script gracefully</code>",
    image: null,
    options: [],
    correct: ["sys.exit"],
  },
  {
    id: "d6_practical_25",
    type: "blank",
    question: "A game developer wants to start a game with a random screen numbered from 1 to 10. Screen 1 is the default screen and should not be selected. Fill in the numbers necessary to generate random screen numbers for the rest of the range. Include no spaces in your answer.<br><br><code># Import the randrange function from the random module<br>from random import randrange<br><br># Generate a random starting screen between 2 and 10 for the player<br>screen = randrange({{1}})</code>",
    image: null,
    options: [],
    correct: ["2,11"],
  },
  {
    id: "d6_practical_26",
    type: "blank",
    question: "Evaluate the following code and then fill in the blank for the method and value needed to return the file name of the current file when run directly from the command line.<br><br><code>import sys<br><br>filename = {{1}} # Get current script file name<br>print (f\"{filename} has been specified.\")</code>",
    image: null,
    options: [],
    correct: ["sys.argv[0]"],
  },
  {
    id: "d6_practical_27",
    type: "blank",
    question: "Which built-in Python module needs to be imported to run this loop? The module name fits in the blank text.<br><br><code>{{1}}.rename('gamelog.txt', 'OLDgamelog.txt')</code>",
    image: null,
    options: [],
    correct: ["os"],
  },
  {
    id: "d6_practical_28",
    type: "blank",
    question: "An io.StringIO text stream has been written to memory. An analyst needs to see the text, starting with the first character. Fill in the keyword needed to start reading the stream.<br><br><code>text_stream.{{1}}(0)</code>",
    image: null,
    options: [],
    correct: ["seek"],
  },
  {
    id: "d6_practical_29",
    type: "blank",
    question: "Fill in the code necessary to assign the player_score variable to be a random integer between 50 and 100.<br><br><code># Import the randint function from the random module<br>from random import randint<br><br># Generate a random integer between 50 and 100 for the player<br>player_score = {{1}}(50, 100)</code>",
    image: null,
    options: [],
    correct: ["randint"],
  },
];
// OBSERVAȚII:
// - Am actualizat câmpurile `question` pentru întrebările de tip "blank" care aveau în imagine o etichetă separată "Answer:", adăugând `Answer: {{1}}` la sfârșit (ex: id-urile d6_practical_08, 14, 15, 18, 21) pentru a genera corect caseta de intrare în interfață. Restul întrebărilor au deja {{1}} încorporat direct în textul propoziției/codului, exact cum apar în capturi.